### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by idolizesc** [bejamas/gatsby-plugin-csp#1]
Hey there! Your plugin looks useful. Wondering what the license is?

I see [MIT in the package.json](https://github.com/bejamas/gatsby-plugin-csp/blob/master/package.json#L23), but there's no license file in the repo.

**Comment by thomkrupa** [comment]
hey @idolizesc 
I forgot to add the license to the repo! Fixed.

**Comment by idolizesc** [comment]
Awesome - thank you!
