### ISSUE TITLE
Warning:  Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by Odelya** [bejamas/gatsby-plugin-csp#13]
Upon installing the plugin, I started getting warnings in the console:

```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <head>. See https://fb.me/react-warning-keys for more information.
    in meta
```

Not sure if it's important to be fixed. Will appreciate your attention.

**Comment by ivands** [comment]
I get the same warning.
My ocd wants me to remove the warning 😋

**Comment by Primajin** [comment]
I was also stumbling over this issue - here is the background:

In the `headComponents` in your `html.js` plugins push things to your html `<head>`.
If you log that out you will see something like this:

```json
    {
      "type": "meta",
      "key": "environment",
      "ref": null,
      "props": {
        "name": "note",
        "content": "environment=development"
      },
      "_owner": null,
      "_store": {}
    }
```

note the `key` here is set to environment.
But for the CSP the key is `null` and it will throw this error.

```json
    {
      "type": "meta",
      "key": null,
      "ref": null,
      "props": {
        "httpEquiv": "Content-Security-Policy",
        "content": "base-uri 'self'; default-src 'self';"
      },
      "_owner": null,
      "_store": {}
    }
```

**Comment by jfgilmore** [comment]
> OK found a fix, until it is merged you can add
> 
> ```
>     key: 'gatsby-plugin-csp',
> ```
> 
> to `node_modules/gatsby-plugin-csp/gatsby-ssr.js:43` then delete the .cache folder and restart. This should remove the error.

Pretty sure this IS the fix that needs to be contributed to this repo 😅
